name: Run unit test

on:
  push:
    paths-ignore:
    - 'README.md'
    - 'Dockerfile'
jobs:
  build:
    name: unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          python -m unittest
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .